image: maven:3-jdk-11

stages:
  - build
  - package

cache:
  paths:
    - target/

maven-build:
  stage: build
  script: mvn clean install

package:
  image: docker:latest
  stage: package
  script:
    - docker build -t rchauhan9/amdb-spring
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
    - docker push rchauhan9/amdb-spring
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
