image: maven:3-jdk-11

stages:
  - build
  - package

cache:
  paths:
    - target/

maven-build:
  stage: build
  script: mvn clean install

services:
  - docker:dind

package:
  image: docker:latest
  stage: package
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
